### ISSUE TITLE
someone is sabotaging vision processing

### ISSUE THREAD

**Issue by akos199X** [frc2609/FIRSTPRESEASON2017#1]
who is it?
danny, is it you?

**Comment by gregzetko** [comment]
not me. *puts finger on nose*

**Comment by DaaaaanB** [comment]
I ain't done nuffin

**Comment by DaaaaanB** [comment]
I actually have no clue what you're talking about

**Comment by akos199X** [comment]
its ok i found the culprit, it was probably me
